### PR TITLE
initial workflows and issue templates

### PR DESCRIPTION
**Pull request by itroyano**
Adding the following artifacts:

- bug issue template
- feature issue template
- build main action (build operator & bundle,  push operator & bundle)
- build release action (same as build main, but on a semvr tag)
- CI build on a pull request.   currently doesn't run `go test` since test files have not been implemented yet.

Signed-off-by: Igor Troyanovsky <itroyano@redhat.com>

### CODE REVIEW

**Comment by acornett21** [comment]
@itroyano Can we also add a `documentation` template? Something like the below?
https://raw.githubusercontent.com/operator-framework/operator-sdk/master/.github/ISSUE_TEMPLATE/doc-report.md

**Comment by itroyano** [comment]
@acornett21 added.  thanks!

btw Operator SDK also has a build step to validate documentation.   I'm looking at how we can add that as well.

**Review by jomkz — APPROVED** [review]
/lgtm

**Review by jomkz — APPROVED** [review]
/lgtm

**Pull request merged**
